// Generated by https://quicktype.io

export interface CreateTaskResponse {
  msg?:        string;
  nuevaTarea: NuevaTarea;
}

export interface NuevaTarea {
  titulo:           string;
  descripcion:      string;
  fecha_completada: null;
  estado:           string;
  _id:              string;
  fecha_creacion:   string;
}
