// Generated by https://quicktype.io

export interface DeleteTaskResponse {
  _id:              string;
  titulo:           string;
  descripcion:      string;
  fecha_completada: string;
  estado:           string;
  fecha_creacion:   string;
}
