// Generated by https://quicktype.io

export interface Tasks {
  _id: string;
  titulo: string;
  descripcion: string;
  fecha_completada: null | string;
  estado: string;
  fecha_creacion: string;
}
